#!/usr/bin/env python3
"""
Fetch latest posts from a Substack RSS feed and:
  1. write `data/writing.json` (programmatic source of truth)
  2. patch the inline HTML in `index.html` between the
     <!-- writing:start --> / <!-- writing:end --> markers

Inline patching (not JS-rendered) is deliberate: essay titles are
entity-relevant content for SEO and LLM crawlers that don't run JS.

No dependencies beyond Python stdlib.

Usage:
  python3 scripts/fetch-substack.py [--feed URL] [--limit N]
"""
from __future__ import annotations
import argparse, datetime as dt, gzip, html, json, pathlib, re, sys, time
import urllib.error, urllib.request
import xml.etree.ElementTree as ET

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15"
)
DEFAULT_FEED = "https://anandiyer.substack.com/feed"
ROOT = pathlib.Path(__file__).resolve().parent.parent

# Substack sits behind Cloudflare, which 403s naked python-urllib from
# datacenter IPs. Real browser headers (and a Referer) get through.
BROWSER_HEADERS = {
    "User-Agent": UA,
    "Accept": "application/rss+xml, application/xml;q=0.9, text/xml;q=0.8, */*;q=0.1",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate",
    "Referer": "https://anandiyer.com/",
    "Cache-Control": "no-cache",
}


def fetch_feed(url: str, max_retries: int = 3) -> str:
    for attempt in range(max_retries):
        try:
            req = urllib.request.Request(url, headers=BROWSER_HEADERS)
            with urllib.request.urlopen(req, timeout=20) as r:
                data = r.read()
                if r.headers.get("Content-Encoding") == "gzip":
                    data = gzip.decompress(data)
                return data.decode("utf-8", errors="replace")
        except urllib.error.HTTPError as e:
            if e.code in (429, 403) and attempt < max_retries - 1:
                wait = 5 * (3 ** attempt)        # 5s, 15s, 45s
                print(f"  HTTP {e.code} from Substack; retry in {wait}s "
                      f"(attempt {attempt+1}/{max_retries})", file=sys.stderr)
                time.sleep(wait)
                continue
            raise


def parse_items(xml_str: str, limit: int) -> list[dict]:
    root = ET.fromstring(xml_str)
    out: list[dict] = []
    for it in root.findall(".//item")[:limit]:
        title = (it.findtext("title") or "").strip()
        link = (it.findtext("link") or "").strip()
        pub = (it.findtext("pubDate") or "").strip()
        # RFC 822: "Fri, 22 May 2026 17:30:00 GMT"
        try:
            d = dt.datetime.strptime(pub, "%a, %d %b %Y %H:%M:%S %Z")
            date_short = d.strftime("%b %-d, %Y")   # "May 22, 2026" — matches tweet rail
            date_iso = d.strftime("%Y-%m-%d")
        except ValueError:
            date_short = pub
            date_iso = ""
        if title and link:
            out.append({
                "title": title,
                "url": link,
                "date": date_short,
                "date_iso": date_iso,
            })
    return out


def render_html(items: list[dict]) -> str:
    """Render the <li> rows that go between the markers."""
    lines = ["  <!-- (auto-generated by scripts/fetch-substack.py — don't edit by hand) -->"]
    for i in items:
        title = html.escape(i["title"])
        url = html.escape(i["url"])
        date = html.escape(i["date"])
        lines.append(
            f'  <li>\n'
            f'    <span class="title"><a href="{url}" target="_blank" rel="noopener">{title}</a></span>\n'
            f'    <span class="meta">{date}</span>\n'
            f'  </li>'
        )
    return "\n".join(lines)


MARKER_RE = re.compile(
    r"(<!--\s*writing:start\s*-->)(.*?)(<!--\s*writing:end\s*-->)",
    re.S,
)


def patch_html(html_path: pathlib.Path, block: str) -> bool:
    src = html_path.read_text(encoding="utf-8")
    if not MARKER_RE.search(src):
        raise SystemExit(
            f"{html_path}: missing <!-- writing:start --> / <!-- writing:end --> markers"
        )
    new = MARKER_RE.sub(lambda m: f"{m.group(1)}\n{block}\n  {m.group(3)}", src)
    if new == src:
        return False
    html_path.write_text(new, encoding="utf-8")
    return True


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--feed", default=DEFAULT_FEED)
    p.add_argument("--limit", type=int, default=5)
    p.add_argument("--json-out", default=str(ROOT / "data" / "writing.json"))
    p.add_argument("--html", default=str(ROOT / "index.html"))
    args = p.parse_args()

    try:
        xml_str = fetch_feed(args.feed)
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as e:
        # Persistent fetch failure (Cloudflare blocking GH runner IP). Don't
        # fail the workflow — last-good writing.json + inline HTML keep serving.
        print(f"fetch failed permanently: {e}; keeping existing writing data",
              file=sys.stderr)
        return 0

    items = parse_items(xml_str, args.limit)
    if not items:
        print("no items in feed — keeping existing writing data", file=sys.stderr)
        return 0

    # 1. JSON source of truth
    pathlib.Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
    with open(args.json_out, "w") as f:
        json.dump(items, f, indent=2, ensure_ascii=False)
        f.write("\n")

    # 2. Inline HTML
    block = render_html(items)
    changed = patch_html(pathlib.Path(args.html), block)

    print(
        f"wrote {len(items)} posts → {args.json_out}; "
        f"index.html {'patched' if changed else 'unchanged'}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
